import { QUAKE_RENDER_SUPERSAMPLE } from "../prepared/preparedScene";

export const QUAKE_COLLISION_UNIT_SCALE = QUAKE_RENDER_SUPERSAMPLE / 48;

export const PLAYER_RADIUS = 16 * QUAKE_COLLISION_UNIT_SCALE;
export const PLAYER_HEIGHT = 56 * QUAKE_COLLISION_UNIT_SCALE;
export const STEP_HEIGHT = 20 * QUAKE_COLLISION_UNIT_SCALE;
export const GROUND_SNAP = 6 * QUAKE_COLLISION_UNIT_SCALE;
export const QUAKE_PLAYER_VIEW_Z = 22 * QUAKE_COLLISION_UNIT_SCALE;
export const QUAKE_BUTTON_USE_RANGE = 96 * QUAKE_COLLISION_UNIT_SCALE;
export const COLLISION_EPSILON = 0.0001;

export const QUAKE_DOOR_START_OPEN = 1;
export const QUAKE_DOOR_DONT_LINK = 4;
export const QUAKE_DOOR_GOLD_KEY = 8;
export const QUAKE_DOOR_SILVER_KEY = 16;
export const QUAKE_DOOR_TOGGLE = 32;
export const QUAKE_SECRET_OPEN_ONCE = 1;
export const QUAKE_DOOR_TRIGGER_XY = 60 * QUAKE_COLLISION_UNIT_SCALE;
export const QUAKE_DOOR_TRIGGER_Z = 8 * QUAKE_COLLISION_UNIT_SCALE;

export const QUAKE_SPAWNFLAG_NOT_EASY = 256;
export const QUAKE_SPAWNFLAG_NOT_MEDIUM = 512;
export const QUAKE_SPAWNFLAG_NOT_HARD = 1024;
export const QUAKE_SINGLE_PLAYER_SKILL = 1;
